export interface Product {
  id: string;
  title: string;
  description?: string;
  image: string;
  imageB?: string;
  imageC?: string;
  imageD?: string;
  imageE?: string;
  details?: Record<string, string>; // <-- cambiar a objeto dinámico
  category?: string;
  brand?: string;
  labels?: string[];
  precio?: string;
}

export const products: Product[] = [
  //VULCAN
  //2 Motosierra
  {
    id: 'VSL550',
    title: 'Motosierra 2T, 55cc, 3HP',
    description: '',
    image: '/assets/VSL550a.jpg',
    imageB: '/assets/VSL550b.jpg',
    imageC: '/assets/VSL550c.jpg',
    imageD: '/assets/VSL550d.jpg',
    imageE: '/assets/VSL550e.jpg',
    category: 'Motosierras',
    brand: 'Vulcan',
    precio: '2.662',
    details: {
      "Código Vulcan Trent": "56419",
      "Modelo": "VSL550",
      "Motor": "2 Tiempos",
      "Potencia": "3 HP",
      "Cilindrada": "55 cc",
      "Rotación": "Máxima: 11.000 RPM | En ralentí: 2.800 RPM",
      "Espada": "Vulcan 18” (46 cm) Punta Rodante – Canal 1,50 mm",
      "Cadena": "32 dientes | Paso: 3/8″ | Grosor: 1,50 mm",
      "Combustible": "Proporción 25:1 – 40 ml de Aceite 2T por litro de gasolina",
      "Capacidad del tanque": "520 ml",
      "Consumo": "Aprox. 1 litro/hora",
      "Aceite": "260 ml",
      "Sistema de arranque": "Arranque manual con resorte retráctil",
      "Amortiguadores": "5 amortiguadores en toda la máquina",
      "Nivel de ruido": "116 dB",
      "Autonomía": "Aproximadamente 30 minutos",
      "Dimensiones del producto": "30 x 26 x 84 cm (Montado con la espada)",
      "Peso del producto": "6,500 kg",
      "Garantía": "12 meses para el mercado boliviano",
      "Contenido del empaque": "- Espada 18”\n- Cadena 32 dientes\n- Protector de espada\n- Dosador de combustible\n- Juego de llaves\n- Lima de cadena\n- Manual del producto"
    },
  },
  //1 Motosierra
  {
    id: 'VS620',
    title: 'Motosierra 2T, 62cc, 4HP',
    description: '',
    image: '/assets/VS620a.jpg',
    imageB: '/assets/VS620b.jpg',
    imageC: '/assets/VS620c.jpg',
    imageD: '/assets/VS620d.jpg',
    imageE: '/assets/VS620e.jpg',
    category: 'Motosierras',
    brand: 'Vulcan',
    labels: ['', ''],
    precio: '4.350',
    details: {
      "Código Vulcan Trent": "56051",
      "Modelo": "VS620",
      "Motor": "2 Tiempos",
      "Potencia": "4 HP",
      "Cilindrada": "62 cc",
      "Rotación": "Máxima: 11.000 RPM | En ralentí: 2.800 RPM",
      "Espada": "Vulcan 20” (50 cm) Punta Rodante – Canal 1,50 mm",
      "Cadena": "34 dientes | Paso: 3/8″ | Grosor: 1,50 mm",
      "Combustible": "Proporción 25:1 – 40 ml de Aceite 2T por litro de gasolina",
      "Capacidad del tanque": "500 ml",
      "Consumo": "Aprox. 1,5 litros/hora",
      "Aceite": "350 ml",
      "Sistema de arranque": "Arranque manual con resorte retráctil – Easy Start",
      "Amortiguadores": "5 amortiguadores en toda la máquina",
      "Nivel de ruido": "116 dB",
      "Autonomía": "Aproximadamente 20 minutos",
      "Dimensiones del producto": "31 x 28 x 88 cm (Montado con la espada)",
      "Peso del producto": "7,400 kg",
      "Garantía": "12 meses para el mercado boliviano",
      "Contenido del empaque": "– Espada 20”"
    }
  },
  //2 Podadora
  {
    id: 'VP2450',
    title: 'Podadora Cortasetos 2T, 25cc',
    description: '',
    image: '/assets/VP2450a.jpg',
    imageB: '/assets/VP2450b.jpg',
    imageC: '/assets/VP2450c.jpg',
    imageD: '/assets/VP2450d.jpg',
    imageE: '/assets/VP2450e.jpg',
    category: 'Podadoras',
    brand: 'Vulcan',
    labels: ['', ''],
    precio: '3.819',
    details: {
      "Código Vulcan Trent": "56327",
      "Modelo": "VP2450",
      "Motor": "2 Tiempos",
      "Potencia": "1,1 HP",
      "Cilindrada": "24,5 cc",
      "Rotación": "Lenta: 2.800 RPM - Máxima: 9.000 RPM",
      "Sistema de arranque": "Manual retráctil",
      "Combustible": "Proporción 25:1 - 40 ml de Aceite 2T por litro de gasolina",
      "Capacidad del tanque": "700 ml",
      "Consumo": "0,350 litros/hora",
      "Cuchilla de corte": "60 cm (24”) - Doble acción",
      "Apertura de corte": "24 mm",
      "Empuñadura de comando": "Permite giro de hasta 180º",
      "Aceite de cadena": "150 ml",
      "Autonomía": "Aproximadamente 2 horas",
      "Dimensiones del producto": "24 x 33 x 110 cm",
      "Peso del producto": "5,800 kg",
      "Garantía": "6 meses",
      "Accesorios incluidos": "– Dosificador de combustible\n– Juego de llaves\n– Protector de cuchilla"
    }
  },
  //1 Podadora
  {
    id: 'VP3300L',
    title: 'Podadora de Altura',
    description: '',
    image: '/assets/VP3300La.jpg',
    imageB: '/assets/VP3300Lb.jpg',
    imageC: '/assets/VP3300Lc.jpg',
    imageD: '/assets/VP3300Ld.jpg',
    imageE: '/assets/VP3300Le.jpg',
    category: 'Podadoras',
    brand: 'Vulcan',
    labels: ['', ''],
    precio: '3.416',
    details: {
      "Código Vulcan Trent": "56570",
      "Modelo": "VP3300L",
      "Motor": "2 Tiempos",
      "Potencia": "1,3 HP",
      "Cilindrada": "33 cc",
      "Rotación": "Lenta: 2.800 RPM | Máxima: 10.000 RPM",
      "Sistema de arranque": "Easy Start",
      "Combustible": "Proporción 25:1 - 40 ml de Aceite 2T por 1 L de gasolina",
      "Capacidad del tanque": "750 ml",
      "Consumo": "1,3 litros/hora",
      "Espada": "Espada 12” (30 cm) - Punta rodante - Canal 1,30 mm",
      "Cadena": "22 dientes | Paso: 3/8″ | Grosor: 1,3 mm",
      "Eje cardán primario": "Rígido 8 mm - 9 estrías - 153 cm",
      "Eje cardán del extensor": "Rígido 8 mm - 9 estrías - 76 cm",
      "Tubo primario": "26 mm - 150 cm",
      "Tubo del extensor": "26 mm - 76 cm",
      "Alcance": "Operador con altura promedio: 4 metros",
      "Aceite de cadena": "150 ml",
      "Autonomía": "Aproximadamente 40 minutos",
      "Nivel de ruido": "100 dB",
      "Dimensiones del producto": "26 x 26 x 288 cm",
      "Peso del producto": "7,700 kg",
      "Garantía": "6 meses",
      "Accesorios incluidos": "– Cinturón de soporte\n– Barra extensora\n– Dosificador de combustible\n– Juego de llaves\n– Protector de espada\n– Espada 12”\n– Cadena\n– Manual del producto"
    }
  },
  //2 Fumigadora
  {
    id: 'VPB16L',
    title: 'Fumigadora Batería 16L',
    description: '',
    image: '/assets/VPB16La.jpg',
    imageB: '/assets/VPB16Lb.jpg',
    imageC: '/assets/VPB16Lc.jpg',
    imageD: '/assets/VPB16Ld.jpg',
    imageE: '/assets/VPB16Le.jpg',
    category: 'Fumigadoras',
    brand: 'Vulcan',
    labels: ['', ''],
    precio: '1.497',
    details: {
      "Código Vulcan Trent": "81361",
      "Modelo": "VPB16L12A",
      "Aplicación": "Profesional",
      "Capacidad del tanque": "16 litros",
      "Autonomía de la batería": "10 horas",
      "Autonomía del depósito": "Vaciado: de 10 a 12 minutos",
      "Accionamiento": "Eléctrico: por bomba eléctrica a batería | Manual: por palanca tipo “L”",
      "Presión": "Máxima: 6 bar | Mínima: 4 bar",
      "Caudal máximo": "2,2 a 4 litros por minuto",
      "Material del pistón": "PP - Polipropileno",
      "Lanza": "Telescópica de 0,86 metros",
      "Manguera": "1,24 metros",
      "Tipo de palanca": "Tipo “L” cuando se utiliza de forma manual",
      "Tipo de batería": "12V - 12A/h - Tamaño (Al x An x Pr) 10 x 10 x 15 cm",
      "Cargador": "Fuente transformadora bivolt 110/220V - 1.7A/h",
      "Tiempo de recarga de la batería": "De 6 a 8 horas",
      "Dimensiones del producto": "54 x 19 x 36 cm",
      "Peso del producto": "6,750 kg",
      "Garantía": "6 meses",
      "Accesorios incluidos": "– 01 Junta\n– 04 Anillos de sellado\n– 02 Anillos Oring\n– 01 Boquilla tipo “L”\n– 01 Boquilla de 4 orificios\n– 01 Boquilla multidireccional de niebla\n– 01 Cargador de batería"
    }
  },

  //1 Fumigadora
  {
    id: 'VAT820P',
    title: 'Fumigadora con Bomba 2T, 5.4HP, 82cc',
    description: '',
    image: '/assets/VAT820Pa.jpg',
    imageB: '/assets/VAT820Pb.jpg',
    imageC: '/assets/VAT820Pc.jpg',
    imageD: '/assets/VAT820Pd.jpg',
    imageE: '/assets/VAT820Pe.jpg',
    category: 'Fumigadoras',
    brand: 'Vulcan',
    labels: ['', ''],
    precio: '5.247',
    details: {
      "Código Vulcan Trent": "56389",
      "Modelo": "VAT820P",
      "Motor": "2 Tiempos",
      "Potencia": "5,4 HP",
      "Cilindrada": "82 cc",
      "Rotación": "Lenta: 2.800 RPM | Máxima: 6.800 RPM",
      "Combustible": "Proporción 25:1 - 40 ml de Aceite 2T por 1 litro de gasolina",
      "Sistema de arranque": "Manual con resorte retráctil",
      "Consumo": "Aproximadamente 1,4 litros por hora",
      "Capacidad del tanque de combustible": "2.000 ml",
      "Autonomía": "Aproximadamente 1 hora y 25 minutos",
      "Capacidad del tanque químico": "20 litros",
      "Caudal": "3,3 kg por minuto (sólido) | 5,5 litros por minuto (líquido)",
      "Alcance de aplicación": "12 metros horizontal | 6 metros vertical",
      "Nivel de ruido": "110 dB",
      "Dimensiones del producto": "40 x 58 x 143 cm",
      "Peso del producto": "13,000 kg",
      "Garantía": "6 meses",
      "Accesorios incluidos": "– Dosificador de combustible\n– Cinturón de soporte\n– Juego de llaves\n– Bujía de encendido\n– 2 Anillos de pistón\n– Embudo\n– Juego de abrazaderas metálicas"
    }
  },

  //1 Taladro
  {
    id: 'VF500',
    title: 'Taladro',
    description: '',
    image: '/assets/VF500a.jpg',
    imageB: '/assets/VF500b.jpg',
    imageC: '/assets/VF500c.jpg',
    imageD: '/assets/VF500d.jpg',
    imageE: '/assets/VF500e.jpg',
    category: 'Taladros',
    brand: 'Vulcan',
    labels: ['', ''],
    precio: '4.465',
    details: {
      "Código Vulcan Trent": "80678",
      "Modelo": "VF500",
      "Motor": "2 Tiempos",
      "Potencia": "1 HP",
      "Cilindrada": "25,4 cc",
      "Rotación": "Máxima: 10.000 RPM | En ralentí: 3.000 RPM",
      "Combustible": "Gasolina - Proporción 25:1",
      "Sistema de arranque": "Manual con resorte retráctil",
      "Consumo": "Aproximadamente 0,45 litros por hora",
      "Capacidad del tanque de combustible": "600 ml",
      "Reducción": "Relación de reducción 10:1",
      "Engranajes": "Acero templado",
      "Reversión": "Posee mecanismo para inversión de la broca",
      "Brocas": "Broca de 12 mm para poste de madera | Broca de 28 mm para poste de madera",
      "Mandril": "1/2’’ para brocas de 2 a 13 mm - 21UNF",
      "Dimensiones del producto": "31 x 23 x 75 cm",
      "Peso del producto con broca de 28 mm": "6,100 kg",
      "Garantía": "6 meses",
      "Accesorios incluidos": "– 2 Brocas\n– 1 Llave de bujía\n– 3 Llaves Allen\n– 2 Llaves de boca\n– 1 Dosificador de combustible"
    }
  },

  //4 Desbrozadora
  {
    id: 'VRM330',
    title: 'Desbrozadora Multifunción 1.5HP, 33cc',
    description: '',
    image: '/assets/VRM330a.jpg',
    imageB: '/assets/VRM330b.jpg',
    imageC: '/assets/VRM330c.jpg',
    imageD: '/assets/VRM330d.jpg',
    imageE: '/assets/VRM330e.jpg',
    category: 'Desbrozadoras',
    brand: 'Vulcan',
    labels: ['', ''],
    precio: '5.085',
    details: {
      "Código Vulcan Trent": "81248",
      "Modelo": "VRM330",
      "Motor": "2 Tiempos",
      "Potencia": "1,3 HP - 33 cc",
      "Nivel de ruido": "114 dB",
      "Rotación": "Lenta: 2.800 RPM | Máxima: 10.000 RPM",
      "Sistema de arranque": "Manual con resorte retráctil - Easy Start",
      "Combustible": "Proporción 25:1 - 40 ml de Aceite 2T por 1 litro de gasolina",
      "Capacidad del tanque": "650 ml",
      "Consumo": "0,65 litros por hora",
      "Autonomía": "Aproximadamente 1 hora",

      "Función Desbrozadora - Eje cardán primario": "Rígido de 8 mm con 9 estrías - Longitud 76 cm (eje de conexión)",
      "Función Desbrozadora - Eje cardán secundario": "Rígido de 8 mm con 9 estrías - Longitud 77 cm",
      "Función Desbrozadora - Tubo del eje cardán": "26 mm - 75 cm",
      "Función Desbrozadora - Peso del producto": "6,350 kg",
      "Función Desbrozadora - Dimensiones del producto": "25 x 38 x 180 cm",

      "Función Podador de ramas - Eje cardán secundario": "Rígido de 8 mm con 9 estrías - Longitud 77 cm",
      "Función Podador de ramas - Tubo del eje cardán": "26 mm - 75 cm",
      "Función Podador de ramas - Alcance": "2,5 metros con un operador de estatura promedio",
      "Función Podador de ramas - Espada": "12” (30 cm) con punta rodante, canal 1,30 mm",
      "Función Podador de ramas - Cadena": "22 dientes - Paso 3/8” - Grosor 1,3 mm",
      "Función Podador de ramas - Peso del producto": "6,350 kg",
      "Función Podador de ramas - Dimensiones del producto": "25 x 33 x 210 cm",

      "Función Podador de setos - Eje cardán secundario": "Rígido de 8 mm con 9 estrías - Longitud 77 cm",
      "Función Podador de setos - Tubo del eje cardán": "26 mm - 75 cm",
      "Función Podador de setos - Alcance": "2,6 metros con un operador de estatura promedio",
      "Función Podador de setos - Cuchilla de corte": "17” (43 cm) | Apertura de cuchilla: 25 mm",
      "Función Podador de setos - Peso del producto": "7,000 kg",
      "Función Podador de setos - Dimensiones del producto": "25 x 33 x 230 cm"
    }
  },

  //3 Desbrozadora
  {
    id: 'VR620H',
    title: 'Desbrozadora a Gasolina 3HP, 62cc',
    description: '',
    image: '/assets/VR620Ha.jpg',
    imageB: '/assets/VR620Hb.jpg',
    imageC: '/assets/VR620Hc.jpg',
    imageD: '/assets/VR620Hd.jpg',
    imageE: '/assets/VR620He.jpg',
    category: 'Desbrozadoras',
    brand: 'Vulcan',
    labels: ['', ''],
    precio: '3.257',
    details: {
      "Código Vulcan Trent": "81828",
      "Modelo": "VR620H",
      "Motor": "2 Tiempos",
      "Potencia": "3 HP",
      "Cilindrada": "62 cc",
      "Rotación": "Lenta: 2.800 RPM | Máxima: 10.800 RPM",
      "Sistema de arranque": "Easy Start",
      "Combustible": "Proporción 25:1 - 40 ml de Aceite 2T por 1 litro de gasolina",
      "Capacidad del tanque": "1.100 ml",
      "Consumo": "1,5 litros/hora",
      "Manillar": "Bipartido, fijado con soportes atornillados",
      "Empuñaduras": "Polipropileno reforzado",
      "Tubo del eje": "28 mm - 150 cm - Aluminio",
      "Eje cardán": "8 mm x 9 estrías - 153 cm - Rígido",
      "Cuchilla": "De 3 puntas (30 cm x 1,6 mm - Orificio 1\")",
      "Carrete": "Carrete automático",
      "Arnés": "Arnés doble con almohadillas",
      "Nivel de ruido": "108 dB",
      "Peso del producto": "9,970 kg",
      "Dimensiones del producto": "27 x 65 x 188 cm",
      "Garantía": "6 meses",
      "Accesorios incluidos": "– Protector de cuchilla\n– Dosificador de combustible\n– Cuchilla de 3 puntas\n– Carrete automático\n– Arnés doble\n– 4 Tornillos Allen 6x20 mm\n– 2 Tornillos Allen 6x15 mm\n– Llave de bujía\n– Destornillador plano/Phillips\n– Llave de boca\n– 2 Llaves Allen\n– Soporte metálico de fijación de la cuchilla\n– Manual del producto"
    }
  },

  //2 Desbrozadora
  {
    id: 'VR520HB',
    title: 'Desbrozadora a Gasolina 5.5HP, 52cc Desmontable',
    description: '',
    image: '/assets/VR520HBa.jpg',
    imageB: '/assets/VR520HBb.jpg',
    imageC: '/assets/VR520HBc.jpg',
    imageD: '/assets/VR520HBd.jpg',
    imageE: '/assets/VR520HBe.jpg',
    category: 'Desbrozadoras',
    brand: 'Vulcan',
    labels: ['', ''],
    precio: '2.315',
    details: {
      "Código Vulcan Trent": "82658",
      "Modelo": "VR520HB",
      "Motor": "2 Tiempos",
      "Potencia": "2,5 HP",
      "Cilindrada": "52 cc",
      "Rotación": "Lenta: 2.800 RPM | Máxima: 10.000 RPM",
      "Sistema de arranque": "Easy Start",
      "Combustible": "Proporción 25:1 - 40 ml de Aceite 2T por 1 litro de gasolina",
      "Capacidad del tanque": "1.000 ml",
      "Consumo": "0,9 litros/hora",
      "Manillar": "Bipartido, fijado con soportes atornillados",
      "Empuñaduras": "Polipropileno reforzado",
      "Tubo del eje primario": "26 mm - 74,5 cm - Aluminio",
      "Eje cardán secundario": "Rígido 8 mm x 9 estrías - 76,2 cm",
      "Tubo del eje secundario": "26 mm - 74,5 cm - Aluminio",
      "Cuchilla": "De 3 puntas (24 cm x 1,6 mm - Orificio 1\")",
      "Carrete": "Carrete automático",
      "Arnés": "Arnés doble con hombreras acolchadas",
      "Nivel de ruido": "105 dB",
      "Peso del producto": "7,700 kg",
      "Dimensiones del producto": "27 x 65 x 188 cm",
      "Garantía": "6 meses",
      "Accesorios incluidos": "– Protector de cuchilla\n– Mezclador de combustible\n– Cuchilla de 3 puntas\n– Carrete automático\n– Arnés de soporte transversal\n– 4 Tornillos Allen 6x20 mm\n– 2 Tornillos Allen 6x15 mm\n– Llave de bujía\n– Destornillador plano/Phillips\n– Llave de boca\n– 2 Llaves Allen\n– Soporte metálico de fijación de cuchilla\n– Manual del producto"
    }
  },

  //1 Desbrozadora
  {
    id: 'VR520H',
    title: 'Desbrozadora a Gasolina 5.5HP, 52cc',
    description: '',
    image: '/assets/VR520Ha.jpg',
    imageB: '/assets/VR520Hb.jpg',
    imageC: '/assets/VR520Hc.jpg',
    imageD: '/assets/VR520Hd.jpg',
    imageE: '/assets/VR520He.jpg',
    category: 'Desbrozadoras',
    brand: 'Vulcan',
    labels: ['', ''],
    precio: '2.976',
    details: {
      "Código Vulcan Trent": "81163",
      "Modelo": "VR520H",
      "Motor": "2 Tiempos",
      "Potencia": "2,5 HP",
      "Cilindrada": "52 cc",
      "Rotación": "Lenta: 2.800 RPM | Máx: 10.000 RPM",
      "Sistema de arranque": "Easy Start",
      "Combustible": "Proporción 25:1 - 40 ml de Aceite 2T por 1 litro de gasolina",
      "Capacidad del tanque": "1.000 ml",
      "Consumo": "0,9 litros/hora",
      "Manillar": "Bipartido, fijado con soportes atornillados",
      "Empuñaduras": "Polipropileno reforzado",
      "Tubo del eje": "28 mm - 150 cm - Aluminio",
      "Eje cardán": "8 mm x 9 estrías - 153 cm - Rígido",
      "Cuchilla": "Faca 3 puntas (30 cm x 1,6 mm - Furo 1\")",
      "Carrete": "Carrete automático",
      "Arnés": "Cinto doble con almohadillas",
      "Nivel de ruido": "105 dB",
      "Peso del producto": "7,600 kg",
      "Dimensiones del producto": "27 x 65 x 188 cm",
      "Garantía": "6 meses",
      "Accesorios incluidos": "01 Protector de cuchilla, 01 Dosador de combustible, 01 Faca 3 puntas, 01 Carrete, 01 Cinto doble, 04 Tornillos Allen 6x20 mm, 02 Tornillos Allen 6x15 mm, 01 Llave de bujía, 01 Destornillador plano/Phillips, 01 Llave de boca, 02 Llaves Allen, 01 Soporte metálico de fijación de cuchilla, 01 Manual del producto"
    }
  },

  //4 Motobomba
  {
    id: 'VB10B',
    title: 'Motobomba a Gasolina 1"',
    description: '',
    image: '/assets/VB10Ba.jpg',
    imageB: '/assets/VB10Bb.jpg',
    imageC: '/assets/VB10Bc.jpg',
    imageD: '/assets/VB10Bd.jpg',
    imageE: '/assets/VB10Be.jpg',
    category: 'Motobombas',
    brand: 'Vulcan',
    labels: ['', ''],
    precio: '2.976',
    details: {
      "Código Vulcan Trent": "56181",
      "Modelo": "VB10B",
      "Motor": "2 Tiempos",
      "Potencia": "2,5 HP",
      "Cilindrada": "52 cc",
      "Combustible": "Proporción 25:1 - 40 ml de Aceite 2T por 1 litro de gasolina",
      "Tipo de motobomba": "Auto-Escorvante",
      "Rotación": "Máx: 10.300 RPM | Lenta: 2.800 RPM",
      "Bitola de mangueras": "Entrada: 1” (25mm) | Salida: 1” (25mm)",
      "Cantidad de salidas": "1 salida de 1” (25mm)",
      "Columna de agua": "20 MCA",
      "Vazão máxima": "7 m³/h o 7.000 litros/h",
      "Sucção máxima": "7 metros",
      "Tempo de succión": "De 1 a 4 minutos",
      "Sistema de arranque": "Easy Start - Partida fácil",
      "Consumo": "Aprox. 1 litro/h",
      "Autonomía": "Aprox. 1 hora",
      "Tanque": "1 litro",
      "Nivel de ruido": "125 dB",
      "Dimensiones del producto": "31 x 29 x 35 cm",
      "Peso del producto": "8,700 kg",
      "Garantía": "6 meses",
      "Accesorios incluidos": "01 Juego de llaves, 01 Dosador de combustible, 01 Filtro peneira"
    }
  },

  //3 Motobomba
  {
    id: 'VMB552H',
    title: 'Motobomba a Gasolina Caudal 2" Alta Presión',
    description: '',
    image: '/assets/VMB552Ha.jpg',
    imageB: '/assets/VMB552Hb.jpg',
    imageC: '/assets/VMB552Hc.jpg',
    imageD: '/assets/VMB552Hd.jpg',
    imageE: '/assets/VMB552He.jpg',
    category: 'Motobombas',
    brand: 'Vulcan',
    labels: ['', ''],
    precio: '5.419',
    details: {
      "Código Vulcan Trent": "56976",
      "Modelo": "VMB552H",
      "Motor": "4 Tiempos",
      "Potencia": "6,5 HP",
      "Cilindrada": "196 cc",
      "Combustible": "Gasolina",
      "Tipo de motobomba": "Auto-aspirante de alta presión",
      "Rotación": "Máxima: 3.800 RPM | Lenta: 1.700 RPM",
      "Bitola de mangueras": "Entrada: 2” (50 mm) | Salida: 2” (50 mm)",
      "Cantidad de salidas": "1 salida de 2” (50 mm) y 2 salidas de 1½” (38 mm)",
      "Columna de agua": "65 MCA",
      "Caudal máximo": "30 m³ o 30.000 litros/hora",
      "Succión máxima": "7 metros",
      "Tiempo de succión": "De 1 a 4 minutos",
      "Sistema de arranque": "Arranque manual con resorte retráctil",
      "Consumo": "Aproximadamente 1,7 litros por hora",
      "Autonomía": "Aproximadamente 1 hora y 30 minutos",
      "Nivel de ruido": "110 dB",
      "Capacidad del tanque": "3 litros",
      "Dimensiones del producto": "42 x 37 x 51 cm",
      "Peso del producto": "23,600 kg",
      "Garantía": "6 meses",
      "Registro en CREA": "62314",
      "Accesorios incluidos": "01 Filtro peneira, 05 Abrazaderas, 04 Niples, 03 Tapas roscadas, 04 Tuercas de niples y 01 Llave de bujía"
    }
  },

  //2 Motobomba
  {
    id: 'VMB653S',
    title: 'Motobomba a Gasolina Caudal 3"',
    description: '',
    image: '/assets/VMB653Sa.jpg',
    imageB: '/assets/VMB653Sb.jpg',
    imageC: '/assets/VMB653Sc.jpg',
    imageD: '/assets/VMB653Sd.jpg',
    imageE: '/assets/VMB653Se.jpg',
    category: 'Motobombas',
    brand: 'Vulcan',
    labels: ['', ''],
    precio: '3.879',
    details: {
      "Código Vulcan Trent": "82771",
      "Modelo": "VMB653S",
      "Motor": "4 Tiempos",
      "Potencia": "6,5 HP",
      "Cilindrada": "196 cc",
      "Combustible": "Gasolina",
      "Tipo de motobomba": "Auto-aspirante",
      "Rotación": "Máxima: 4.000 RPM",
      "Bitola de mangueras": "Entrada: 3” (80 mm) | Salida: 3” (80 mm)",
      "Cantidad de salidas": "1 salida de 3” (80 mm)",
      "Columna de agua": "30 MCA",
      "Caudal máximo": "60 m³ o 60.000 litros/hora",
      "Succión máxima": "7 metros",
      "Tiempo de succión": "De 1 a 4 minutos",
      "Sistema de arranque": "Arranque manual con resorte retráctil",
      "Consumo": "Aproximadamente 1,6 litros por hora",
      "Autonomía": "Aproximadamente 2 horas",
      "Nivel de ruido": "110 dB",
      "Capacidad del tanque": "3 litros",
      "Dimensiones del producto": "43 x 40 x 51 cm",
      "Peso del producto": "19,700 kg",
      "Garantía": "6 meses",
      "Registro en CREA": "62314",
      "Accesorios incluidos": "01 Llave de bujía, 03 Abrazaderas de acero, 01 Filtro peneira, 02 Niples, 02 Tuercas de niple"
    }
  },

  //1 Motobomba
  {
    id: 'VMB652S',
    title: 'Motobomba a Gasolina Caudal 2"',
    description: '',
    image: '/assets/VMB652Sa.jpg',
    imageB: '/assets/VMB652Sb.jpg',
    imageC: '/assets/VMB652Sc.jpg',
    imageD: '/assets/VMB652Sd.jpg',
    imageE: '/assets/VMB652Se.jpg',
    category: 'Motobombas',
    brand: 'Vulcan',
    labels: ['', ''],
    precio: '3.305',
    details: {
      "Código Vulcan Trent": "82764",
      "Modelo": "VMB652S",
      "Motor": "4 Tiempos",
      "Potencia": "6,5 HP",
      "Cilindrada": "196 cc",
      "Combustible": "Gasolina",
      "Tipo de motobomba": "Auto-aspirante",
      "Rotación": "Máxima: 4.000 RPM",
      "Bitola de mangueras": "Entrada: 2’’ (50 mm) | Salida: 2’’ (50 mm)",
      "Cantidad de salidas": "1 salida de 2’’ (50 mm)",
      "Columna de agua": "26 MCA",
      "Caudal máximo": "36.000 litros/hora",
      "Succión máxima": "7 metros",
      "Tiempo de succión": "De 1 a 4 minutos",
      "Sistema de arranque": "Arranque manual con resorte retráctil",
      "Consumo": "Aproximadamente 1,6 litros por hora",
      "Autonomía": "Aproximadamente 2 horas",
      "Nivel de ruido": "98 dB",
      "Capacidad del tanque": "3 litros",
      "Dimensiones del producto": "39 x 37 x 47 cm",
      "Peso del producto": "18,300 kg",
      "Garantía": "6 meses",
      "Registro en CREA": "62314",
      "Accesorios incluidos": "01 Llave de bujía, 03 abrazaderas de acero, 01 filtro peneira, 02 niples, 02 tuercas de niple, 04 pies de goma con tuerca"
    }
  },


  //HYUNDAI
  //1 Motobomba
  {
    id: 'HWP5028',
    title: 'Motobomba a Gasolina Caudal 2"',
    description: '',
    image: '/assets/HWP5028a.jpg',
    category: 'Motobombas',
    brand: 'Hyundai',
    labels: ['', ''],
    precio: '3.486',
    details: {
      "Modelo": "HWP5028",
      "Tipo de motobomba": "Bomba de agua",
      "Diámetro de entradas/salida": "2 pulgadas (50 mm)",
      "Succión máxima": "8 m",
      "Altura máxima": "30 m",
      "Caudal máximo": "30 m³/h",
      "Tiempo autocebado": "180 seg",
      "Motor": "4 tiempos",
      "Potencia máxima (3.600 RPM)": "7 HP",
      "Tipo de arranque": "Manual"
    }
  },

  //2 Motobomba
  {
    id: 'HWP8028',
    title: 'Motobomba a Gasolina Caudal 3"',
    description: '',
    image: '/assets/HWP8028a.jpg',
    category: 'Motobombas',
    brand: 'Hyundai',
    labels: ['', ''],
    precio: '3.978',
    details: {
      "Modelo": "HWP8028",
      "Tipo de motobomba": "Bomba de agua",
      "Diámetro de entradas/salida": "2 pulgadas (50 mm)",
      "Succión máxima": "7,5 m",
      "Altura máxima": "32 m",
      "Caudal máximo": "58 m³/h",
      "Tiempo autocebado": "180 seg",
      "Motor": "4 tiempos",
      "Potencia máxima (KW/3.600 RPM)": "4,3 kW",
      "Tipo de arranque": "Manual"
    }
  },

  //3 Motobomba
  {
    id: 'HWPS028HP70',
    title: 'Motobomba a Gasolina Alta Presión',
    description: '',
    image: '/assets/HWPS028HP70a.jpg',
    category: 'Motobombas',
    brand: 'Hyundai',
    labels: ['', ''],
    precio: '6.481',
    details: {
      "Modelo": "HWPS028HP70",
      "Tipo de motobomba": "Bomba de alta presión",
      "Diámetro de entradas/salida": "2 pulgadas (50 mm)",
      "Succión máxima": "7 m",
      "Altura máxima": "70 m",
      "Caudal máximo": "30 m³/h",
      "Tiempo autocebado": "180 seg",
      "Motor": "4 tiempos",
      "Potencia máxima (KW/3.600 RPM)": "4,3 kW",
      "Tipo de arranque": "Manual"
    }
  },

  //1 Generador
  {
    id: 'HG2200',
    title: 'Generador a Gasolina 2200W',
    description: '',
    image: '/assets/HG2200a.jpg',
    category: 'Generadores',
    brand: 'Hyundai',
    labels: ['', ''],
    precio: '5.147',
    details: {
      "Modelo": "HG2200",
      "Motor": "R210-L2",
      "Desplazamiento": "212 cc",
      "Arranque": "Manual",
      "Frecuencia": "50 Hz",
      "Voltaje": "220 V",
      "Poder nominal": "2 kW",
      "Poder máximo": "2,2 kW",
      "DC Output": "12 V, 8,3 A",
      "Capacidad del tanque": "15 L",
      "Tiempo de funcionamiento 100%": "9 h",
      "Tiempo de funcionamiento 50%": "13 h",
      "Nivel de ruido": "70 dB",
      "Dimensiones": "593 x 465 x 458 mm",
      "Peso": "44 kg"
    }
  },

  //2 Generador
  {
    id: 'HG2800',
    title: 'Generador a Gasolina 2800W',
    description: '',
    image: '/assets/HG2800a.jpg',
    category: 'Generadores',
    brand: 'Hyundai',
    labels: ['', ''],
    precio: '5.395',
    details: {
      "Modelo": "HG2800",
      "Motor": "R210-L2",
      "Desplazamiento": "212 cc",
      "Arranque": "Manual",
      "Frecuencia": "50 Hz",
      "Voltaje": "220 V",
      "Poder nominal": "2,5 kW",
      "Poder máximo": "2,8 kW",
      "DC Output": "12 V, 8,3 A",
      "Capacidad del tanque": "15 L",
      "Tiempo de funcionamiento 100%": "8 h",
      "Tiempo de funcionamiento 50%": "11,5 h",
      "Nivel de ruido": "70 dB",
      "Dimensiones": "593 x 465 x 458 mm",
      "Peso": "45 kg"
    }
  },
  //3 Generador
  {
    id: 'HG3000E',
    title: 'Generador a Gasolina 3000W',
    description: '',
    image: '/assets/HG3000Ea.jpg',
    category: 'Generadores',
    brand: 'Hyundai',
    labels: ['', ''],
    precio: '7.347',
    details: {
      "Modelo": "HG3000E",
      "Motor": "R210-L2",
      "Desplazamiento del motor": "212 cc",
      "Tipo de arranque": "Manual",
      "Frecuencia": "50 Hz",
      "Voltaje": "220 V",
      "Potencia nominal": "2,7 kW",
      "Potencia máxima": "3 kW",
      "Salida DC": "12 V, 8,3 A",
      "Capacidad del tanque": "15 L",
      "Tiempo de funcionamiento 100%": "7 h",
      "Tiempo de funcionamiento 50%": "10 h",
      "Nivel de ruido": "70 dB",
      "Dimensiones": "593 x 465 x 458 mm",
      "Peso": "46 kg"
    }
  },
  //4 Generador
  {
    id: 'HG3000',
    title: 'Generador a Gasolina 3000W',
    description: '',
    image: '/assets/HG3000a.jpg',
    category: 'Generadores',
    brand: 'Hyundai',
    labels: ['', ''],
    precio: '5.679',
    details: {
      "Modelo": "HG3000",
      "Motor": "R210-L2",
      "Desplazamiento del motor": "212 cc",
      "Tipo de arranque": "Manual",
      "Frecuencia": "50 Hz",
      "Voltaje": "220 V",
      "Potencia nominal": "2,7 kW",
      "Potencia máxima": "3 kW",
      "Salida DC": "12 V, 8,3 A",
      "Capacidad del tanque": "15 L",
      "Tiempo de funcionamiento 100%": "7 h",
      "Tiempo de funcionamiento 50%": "10 h",
      "Nivel de ruido": "70 dB",
      "Dimensiones": "593 x 465 x 458 mm",
      "Peso": "46 kg"
    }
  },
  //5 Generador
  {
    id: 'HG6000E',
    title: 'Generador a Gasolina 6000W',
    description: '',
    image: '/assets/HG6000Ea.jpg',
    category: 'Generadores',
    brand: 'Hyundai',
    labels: ['', ''],
    precio: '11.500',
    details: {
      "Modelo": "HG6000E",
      "Desplazamiento del motor": "420 cc",
      "Tipo de arranque": "Arranque eléctrico",
      "Frecuencia": "50 Hz",
      "Voltaje AC": "220 V",
      "Corriente AC": "27,2 A",
      "Potencia nominal": "6.000 W",
      "Potencia máxima": "6.500 W",
      "Factor de potencia": "1",
      "Sistema de regulación de voltaje": "AVR",
      "Salida DC": "N/A",
      "Peso": "88 kg",
      "Dimensiones": "785 x 540 x 565 mm"
    }
  },
  //6 Generador
  {
    id: 'HG8500ET',
    title: 'Generador a Gasolina 7000W',
    description: '',
    image: '/assets/HG8500ETa.jpg',
    category: 'Generadores',
    brand: 'Hyundai',
    labels: ['', ''],
    precio: '13.990',
    details: {
      "Modelo": "HG8500ET",
      "Desplazamiento del motor": "457,9 cc",
      "Tipo de arranque": "Arranque eléctrico",
      "Frecuencia": "50 Hz",
      "Corriente AC": "34 A / 14,2 A",
      "Potencia nominal": "7.500 W",
      "Potencia máxima": "8.300 W",
      "Factor de potencia": "1",
      "Sistema de regulación de voltaje": "AVR",
      "Salida DC": "N/A",
      "Peso": "94 kg",
      "Dimensiones": "705 x 540 x 565 mm"
    }
  },



];
